apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one-html
data:
  index.html: |
    <html>
      <body><h1>App One</h1></body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      volumes:
        - name: html
          configMap:
            name: app-one-html
      containers:
      - name: app-one
        image: nginx:1.14.2
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
